### ISSUE TITLE
declarativeNetRequest queryTransform cant removeParams with array query type

### ISSUE THREAD

**Issue by lastworld212** [GoogleChrome/chrome-extensions-samples#850] opened 2023-03-15 17:39 UTC
**Describe the bug**
declarativeNetRequest queryTransform cant removeParams with array query type
**To Reproduce**
Some query like:
https://www.domain.com/groups/groupID/user/usersID/?__cft__[0]=xxxxxx&__cft__[1]=yyyyy
Use this transform redirect rule to remove query :  `{"queryTransform" : {"removeParams": ["__cft__[0]" , "__cft__[1]"]} }`
**Expected behavior**
If this works properly, chrome will redirect url to new url : https://www.domain.com/groups/groupID/user/usersID/
But nothing happen !

**Screenshots**

**Notes**
Anything additional here. 🌈
I think need support regex queryTransform to be able to handle array queries like this too.

**Comment by daidr** [comment] 2023-05-15 13:14
Thank you for your feedback. I was able to reproduce and have created a issue on https://bugs.chromium.org/p/chromium/issues/detail?id=1445521.

**Comment by oliverdunk** [comment] 2023-05-16 16:41
Since this is not related to the samples repo, and we have a bug now, closing this :)

**Closed by oliverdunk** 2023-05-16 16:41 UTC
