### ISSUE TITLE
service_worker context & logs are available in other pages?

### ISSUE THREAD

**Issue by petr24** [GoogleChrome/chrome-extensions-samples#787] opened 2022-12-14 02:43 UTC
**Describe the bug**
Any console.log in a service_worker file such as background.js is available/visible in other contexts such as popup.

**To Reproduce**
Steps to reproduce the behavior, or file the issue is found in:
1. Create a simple manifest.json V3 extension

```
{
  "name": "Counter TEST",
  "version": "1.0",
  "description": "Chrome extension + Svelte boilerplate",
  "permissions": ["activeTab", "tabs"],
  "manifest_version": 3,
  "background": {
    "service_worker": "background.js"
  },
  "action": {
    "default_popup": "popout.html"
  }
}
```

2. Create a background.js file

```
setInterval(function() {
    console.log("background.js every 5s");
}, 5000);
```

3. Create a popout.html

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <title>Popout App</title>
    <script src="popout.js"></script>
</head>
<body>
<h1>Hello!</h1>
</body>
</html>
```

4. Create a popout.js

```
setInterval(function() {
    console.log("popout.js every 5s");
}, 5000);
```

5. Install the extension, and open up the servicer worker console, click on the extension icon to open the popup. Inspect element and view the console.

6. Console side by side, background.js log are visible in popout.js. 
<img width="1701" alt="Screen Shot 2022-12-13 at 6 42 14 PM" src="https://user-images.githubusercontent.com/3904464/207492268-e46c7236-8b1d-492f-9a30-d5790d21bdb0.png">

**Expected behavior**
For popout.js to have separate context from background.js

**Comment by patrickkettner** [comment] 2023-03-03 17:47
Hi @petr24!
Thanks so much for opening an issue, but this is actually working as intended. Therefore, I am closing it out.

**Closed by patrickkettner** 2023-03-03 17:47 UTC
