### ISSUE TITLE
Popup extension with "chrome.tabs.update" API was work unnormal in Mac

### ISSUE THREAD

**Issue by chen6516** [GoogleChrome/chrome-extensions-samples#757] opened 2022-09-28 05:23 UTC
**Describe the bug**
ENV:Newest chrome(105.0.5195.127) + popup extention development
Question:
When i develop popup extention and i invoke "chrome.tabs.update" API to update url in current Tab, the chrome of windows version is work ok, but it will auto close popup window in Mac. i need comunication popup with content-script, so, but, the popup be closed automaticaly.

**To Reproduce**
I download offical popup demo(https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/examples/milestones). 
i add a button in popup window([popup.html](https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/examples/milestones/popup.html)) and click this button will invoke "chrome.tabs.update" function to update current url of Tab.
the same as my describe that popup window will auto close in mac , the windows version is work ok.

**Comment by daidr** [comment] 2023-05-22 10:31
Thanks for the feedback. I was able to reproduce the issue, and here is the relevant Chromium bug link:
https://bugs.chromium.org/p/chromium/issues/detail?id=1378434

**Comment by oliverdunk** [comment] 2023-05-22 10:38
Closing this since bugs are best tracked in the Chromium bug tracker.

**Closed by oliverdunk** 2023-05-22 10:38 UTC
