### ISSUE TITLE
code from function-sample-tutorial.quick-api-reference encounters authentication issue with API: Error Code 401

### ISSUE THREAD

**Issue by ahauser16** [GoogleChrome/chrome-extensions-samples#1054] opened 2023-12-19 19:18 UTC
I followed the Google Chrome tutorial located here: [developer.chrome.com/.../tutorial/service-worker-events](https://developer.chrome.com/docs/extensions/get-started/tutorial/service-worker-events).  I uploaded the official folder from Google Chrome's functional-samples folder and did not use my own code because I thought it was my mistake that caused the error.  I successfully uploaded the extension, typed "api" into the address bar, hit the TAB key and typed "runtime".  A new tab opened to the Runtime API documentation as expected, however, I did not see the "TIP" icon anywhere on the page.  I looked in the console and found two errors:

error one:
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'append')
    at content.js:25:7

error two:
Failed to load resource: the server responded with a status of 404 ()
```
{
  "error": {
    "code": 401,
    "message": "API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.internal.developerprofiles.v1.profile.ProfileService.GetProfile",
          "service": "developerprofiles-pa.googleapis.com"
        }
      }
    ]
  }
}
```

**To Reproduce**
Steps to reproduce the behavior, or file the issue is found in:

1. Follow tutorial located here: 'https://developer.chrome.com/docs/extensions/get-started/tutorial/service-worker-events'
2. Load unpacked extension folder from Google Chrome's github located here: 'https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/functional-samples/tutorial.quick-api-reference'
3. Once extension is successfully uploaded type "api", hit "TAB" key as instructed by tutorial, enter "runtime" and hit "ENTER" key.
4. A new tab opens to the Runtime API documentation.
5. At this point in the tutorial (https://developer.chrome.com/docs/extensions/get-started/tutorial/service-worker-events#open-tip') you are instructed to "Open Tip of the Day" but it does not appear on the screen or in the DOM.
7. See error below listed in the ERRORS tab of the chrome://extensions page:
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'append')
Context
https://developer.chrome.com/docs/extensions/reference/api/runtime
Stack Trace
content.js:25 (anonymous function)

```
1 // Popover API https://chromestatus.com/feature/5463833265045504
2
3 (async () => {
4 const nav = document.querySelector('.navigation-rail__links');
5
6  const { tip } = await chrome.runtime.sendMessage({ greeting: 'tip' });
7
8  const tipWidget = createDomElement(`
9    <button class="navigation-rail__link" popovertarget="tip-popover" popovertargetaction="show" style="padding: 0; border: none; background: none;>
10      <div class="navigation-rail__icon">
11        <svg class="icon" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none"> 
12        <path d='M15 16H9M14.5 9C14.5 7.61929 13.3807 6.5 12 6.5M6 9C6 11.2208 7.2066 13.1599 9 14.1973V18.5C9 19.8807 10.1193 21 11.5 21H12.5C13.8807 21 15 19.8807 15 18.5V14.1973C16.7934 13.1599 18 11.2208 18 9C18 5.68629 15.3137 3 12 3C8.68629 3 6 5.68629 6 9Z'"></path>
13        </svg>
14      </div>
15      <span>Tip</span> 
16    </button>
17  `);
18
19  const popover = createDomElement(
20    `<div id='tip-popover' popover>${tip}</div>`
21  );
22
23  document.body.append(popover);
24  console.log(nav)
25  nav.append(tipWidget);
26 })();
27
28 function createDomElement(html) {
29  const dom = new DOMParser().parseFromString(html, 'text/html');
30  return dom.body.firstElementChild;
31 }
```
 

**Expected behavior**
The behavior described in the google chrome tutorial located here: "https://developer.chrome.com/docs/extensions/get-started/tutorial/service-worker-events#open-tip"

**Notes**
Really enjoying the chrome extension documentation so this isn't representative of my total experience :).

**Comment by patrickkettner** [comment] 2023-12-19 21:19
Hi @ahauser16!
This is because the documentation website was recently migrated to a new backend system, so the specific selector being used is no longer valid.
As a temporary workaround, you can change the selector on line 4 from `.navigation-rail__links` to `.devsite-tabs-wrapper` to see something similar.

**Comment by itzmeimran** [comment] 2023-12-31 04:54
Is this issue stil open ???

**Comment by 4Furki4** [comment] 2024-01-10 19:33
quering the dom for the nav as below solved the issue for me. I can see the Tip text on the navbar that opens the popup.

`const nav = document.querySelector('.lower-tabs .devsite-tabs-wrapper');`
OR
`const nav = document.querySelector('.upper-tabs .devsite-tabs-wrapper');`

However, I still see the error `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'append')` that points to the line `nav.append(tipWidget);`

**Comment by parth-r-parmar** [comment] 2024-01-12 06:21
Style issue :
Add double quote in style attribute of button. 

**before**
```
  const tipWidget = createDomElement(`
    <button class="navigation-rail__link" popovertarget="tip-popover" popovertargetaction="show" style="padding: 0; border: none; background: none;>
      <div class="navigation-rail__icon">
        <svg class="icon" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none"> 
        <path d='M15 16H9M14.5 9C14.5 7.61929 13.3807 6.5 12 6.5M6 9C6 11.2208 7.2066 13.1599 9 14.1973V18.5C9 19.8807 10.1193 21 11.5 21H12.5C13.8807 21 15 19.8807 15 18.5V14.1973C16.7934 13.1599 18 11.2208 18 9C18 5.68629 15.3137 3 12 3C8.68629 3 6 5.68629 6 9Z'"></path>
        </svg>
      </div>
      <span>Tip</span> 
    </button>
  `);
```


**after**
```
  const tipWidget = createDomElement(`
    <button class="navigation-rail__link" popovertarget="tip-popover" popovertargetaction="show" style="padding: 0; border: none; background: none;">
      <div class="navigation-rail__icon">
        <svg class="icon" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none"> 
        <path d='M15 16H9M14.5 9C14.5 7.61929 13.3807 6.5 12 6.5M6 9C6 11.2208 7.2066 13.1599 9 14.1973V18.5C9 19.8807 10.1193 21 11.5 21H12.5C13.8807 21 15 19.8807 15 18.5V14.1973C16.7934 13.1599 18 11.2208 18 9C18 5.68629 15.3137 3 12 3C8.68629 3 6 5.68629 6 9Z'"></path>
        </svg>
      </div>
      <span>Tip</span> 
    </button>
  `);
```

**Comment by oliverdunk** [comment] 2024-02-19 17:22
Closing this as a duplicate of https://github.com/GoogleChrome/chrome-extensions-samples/issues/1084 since I just left a more detailed reply there, but thanks all for the feedback.

**Closed by oliverdunk** 2024-02-19 17:22 UTC
